sonar.projectKey=smart-parking
sonar.projectName=Smart-Parking
sonar.sources=backend,frontend,ai-service
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/node_modules/**,**/*.js,**/*.ts
sonar.scm.disabled=true
